name: rna_pipeline
version: "1.0.0"
config-version: 2

profile: rna_pipeline

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  rna_pipeline:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

vars:
  processed_dir: "data/processed/gse78220"