version: 2

sources:
  - name: processed
    tables:
      - name: baseline_long
        meta:
          external_location: "data/processed/gse78220/baseline_long.parquet"

      - name: parsed_metadata
        meta:
          external_location: "data/processed/gse78220/parsed_metadata.parquet"